#include "trc_format.h"

#include <stdio.h>

/*
 * Header mirrors what python-can's TRCWriter emits for FILEVERSION 2.1, plus a
 * short human-readable preamble documenting the columns and the placeholder
 * start time. Every non-data line is a `;` comment, as the format requires.
 */
int trc_format_header(char *buf, size_t buf_len)
{
    int n = snprintf(
        buf, buf_len,
        ";$FILEVERSION=2.1\n"
        ";$STARTTIME=" TRC_PLACEHOLDER_STARTTIME "\n"
        ";$COLUMNS=N,O,T,B,I,d,R,L,D\n"
        ";\n"
        ";   Generated by open-chmbl CAN logger (ESP-WROVER-KIT, listen-only).\n"
        ";   $STARTTIME is a placeholder (no on-board RTC); only the relative\n"
        ";   time offsets between frames are meaningful.\n"
        ";\n"
        ";   Message   Time    Type Bus  ID    Dir  Rsvd DLC  Data\n"
        ";   Number    Offset\n"
        ";   |         [ms]     |    |    |     |    |    |    |\n"
        ";---+-----  --+-----  -+-  -+-  -+---  -+-  -+-  -+-  -+ -- ...\n");

    if (n < 0 || (size_t)n >= buf_len) {
        return -1;
    }
    return n;
}

int trc_format_line(char *buf, size_t buf_len,
                    uint32_t msgnr, double time_ms, const trc_frame_t *f)
{
    /* Identifier: extended frames are zero-padded to 8 hex digits so the
     * reader's "length > 4 => extended" rule fires; standard frames print with
     * their natural width (<= 3 digits for an 11-bit ID). */
    char id_str[9];
    if (f->extended) {
        snprintf(id_str, sizeof(id_str), "%08lX", (unsigned long)(f->id & 0x1FFFFFFFu));
    } else {
        snprintf(id_str, sizeof(id_str), "%lX", (unsigned long)(f->id & 0x7FFu));
    }

    const char *type = f->rtr ? "RR" : "DT";

    /* Fixed columns up to (and including) the DLC. Field widths match the
     * python-can v2.1 writer: N>7, O>13.3f, B>2, I>8, dir>2, DLC<4. */
    int n = snprintf(buf, buf_len,
                     "%7lu %13.3f %s %2d %8s %2s -  %-4u",
                     (unsigned long)msgnr, time_ms, type, 1, id_str, "Rx",
                     (unsigned)f->dlc);
    if (n < 0 || (size_t)n >= buf_len) {
        return -1;
    }

    /* Remote frames carry no data bytes. */
    if (f->rtr) {
        return n;
    }

    for (unsigned i = 0; i < f->dlc && i < sizeof(f->data); i++) {
        int m = snprintf(buf + n, buf_len - (size_t)n, " %02X", f->data[i]);
        if (m < 0 || (size_t)(n + m) >= buf_len) {
            return -1;
        }
        n += m;
    }
    return n;
}
